/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BalanceCommonFielsResponse } from './balance-common-fiels-response';

/**
 * balance model
 */
export interface BalanceResponse {
    /**
     * The balance\'s available
     */
    'available'?: Array<BalanceCommonFielsResponse>;
    /**
     * The balance\'s cashout retention amount
     */
    'cashout_retention_amount'?: Array<BalanceCommonFielsResponse>;
    /**
     * The balance\'s conekta retention
     */
    'conekta_retention'?: Array<BalanceCommonFielsResponse>;
    /**
     * The balance\'s gateway
     */
    'gateway'?: Array<BalanceCommonFielsResponse>;
    /**
     * The balance\'s pending
     */
    'pending'?: Array<BalanceCommonFielsResponse>;
    /**
     * The balance\'s retained
     */
    'retained'?: Array<BalanceCommonFielsResponse>;
    /**
     * The balance\'s retention amount
     */
    'retention_amount'?: Array<BalanceCommonFielsResponse>;
    /**
     * The balance\'s target collateral amount
     */
    'target_collateral_amount'?: object;
    /**
     * The balance\'s target retention amount
     */
    'target_retention_amount'?: Array<BalanceCommonFielsResponse>;
    /**
     * The balance\'s temporarily retained
     */
    'temporarily_retained'?: Array<BalanceCommonFielsResponse>;
}

