/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * requested field for update a charge
 * @export
 * @interface ChargeUpdateRequest
 */
export interface ChargeUpdateRequest {
    /**
     * custom reference id
     * @type {string}
     * @memberof ChargeUpdateRequest
     */
    'reference_id'?: string;
}

