/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * use for card responses
 * @export
 * @interface ChargeDataPaymentMethodCardResponse
 */
export interface ChargeDataPaymentMethodCardResponse {
    /**
     * 
     * @type {string}
     * @memberof ChargeDataPaymentMethodCardResponse
     */
    'account_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChargeDataPaymentMethodCardResponse
     */
    'auth_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChargeDataPaymentMethodCardResponse
     */
    'brand'?: string;
    /**
     * Id sent for recurrent charges.
     * @type {string}
     * @memberof ChargeDataPaymentMethodCardResponse
     */
    'contract_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChargeDataPaymentMethodCardResponse
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChargeDataPaymentMethodCardResponse
     */
    'exp_month'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChargeDataPaymentMethodCardResponse
     */
    'exp_year'?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof ChargeDataPaymentMethodCardResponse
     */
    'fraud_indicators'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof ChargeDataPaymentMethodCardResponse
     */
    'issuer'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChargeDataPaymentMethodCardResponse
     */
    'last4'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChargeDataPaymentMethodCardResponse
     */
    'name'?: string;
}

