/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ChargeOrderResponseChannel {
    'segment'?: string;
    'checkoutRequestId'?: string;
    'checkoutRequestType'?: string;
    'id'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "segment",
            "baseName": "segment",
            "type": "string"
        },
        {
            "name": "checkoutRequestId",
            "baseName": "checkout_request_id",
            "type": "string"
        },
        {
            "name": "checkoutRequestType",
            "baseName": "checkout_request_type",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ChargeOrderResponseChannel.attributeTypeMap;
    }
}

