/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ChargeRequestPaymentMethod } from './charge-request-payment-method';

/**
 * The charges to be made
 * @export
 * @interface ChargeRequest
 */
export interface ChargeRequest {
    /**
     * 
     * @type {number}
     * @memberof ChargeRequest
     */
    'amount'?: number;
    /**
     * 
     * @type {ChargeRequestPaymentMethod}
     * @memberof ChargeRequest
     */
    'payment_method': ChargeRequestPaymentMethod;
    /**
     * Custom reference to add to the charge
     * @type {string}
     * @memberof ChargeRequest
     */
    'reference_id'?: string;
}

