/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChargeOrderResponsePaymentMethod } from './charge-order-response-payment-method';
// May contain unused imports in some cases
// @ts-ignore
import type { ChargeResponseChannel } from './charge-response-channel';

export interface ChargeOrderResponse {
    'amount'?: number;
    'channel'?: ChargeResponseChannel;
    'created_at'?: number;
    'currency'?: string;
    'customer_id'?: string;
    'description'?: string;
    'device_fingerprint'?: string;
    'failure_code'?: string;
    'failure_message'?: string;
    'id'?: string;
    'livemode'?: boolean;
    'monthly_installments'?: number;
    'object'?: string;
    'order_id'?: string;
    'paid_at'?: number;
    'payment_method'?: ChargeOrderResponsePaymentMethod;
    /**
     * Reference ID of the charge
     */
    'reference_id'?: string;
    'refunds'?: Array<any>;
    'status'?: string;
}

