/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckoutOrderTemplate } from './checkout-order-template';

/**
 * It is a sub-resource of the Order model that can be stipulated in order to configure its corresponding checkout
 */
export interface Checkout {
    /**
     * Those are the payment methods that will be available for the link. This field is mutually exclusive with excluded_payment_methods.
     */
    'allowed_payment_methods'?: Array<string>;
    /**
     * Payment methods to be excluded from the checkout. This field is mutually exclusive with allowed_payment_methods.
     */
    'excluded_payment_methods'?: Array<CheckoutExcludedPaymentMethodsEnum>;
    /**
     * List of card networks to exclude from the checkout. This field is only applicable for card payments.
     */
    'exclude_card_networks'?: Array<CheckoutExcludeCardNetworksEnum>;
    /**
     * It is the time when the link will expire.  It is expressed in seconds since the Unix epoch. The valid range is from 5 minutes to 365 days from the creation date. 
     */
    'expires_at': number;
    /**
     * This flag allows you to specify if months without interest will be active.
     */
    'monthly_installments_enabled'?: boolean;
    /**
     * This field allows you to specify the number of months without interest.
     */
    'monthly_installments_options'?: Array<number>;
    /**
     * Indicates the 3DS2 mode for the order, either smart or strict. This property is only applicable when 3DS is enabled. When 3DS is disabled, this field should be null.
     */
    'three_ds_mode'?: string;
    /**
     * Reason for charge
     */
    'name': string;
    /**
     * This flag allows you to fill in the shipping information at checkout.
     */
    'needs_shipping_contact'?: boolean;
    /**
     * This flag allows you to specify if the link will be on demand.
     */
    'on_demand_enabled'?: boolean;
    /**
     * It is a list of plan IDs that will be associated with the order.
     */
    'plan_ids'?: Array<string>;
    'order_template': CheckoutOrderTemplate;
    /**
     * It is the number of payments that can be made through the link.
     */
    'payments_limit_count'?: number;
    /**
     * The URL to redirect to after a successful payment.
     */
    'success_url'?: string;
    /**
     * false: single use. true: multiple payments
     */
    'recurrent': boolean;
    /**
     * It is the type of link that will be created. It must be a valid type.
     */
    'type': string;
}

export const CheckoutExcludedPaymentMethodsEnum = {
    cash: 'cash',
    card: 'card',
    bankTransfer: 'bank_transfer',
    bnpl: 'bnpl',
    payByBank: 'pay_by_bank',
} as const;

export type CheckoutExcludedPaymentMethodsEnum = typeof CheckoutExcludedPaymentMethodsEnum[keyof typeof CheckoutExcludedPaymentMethodsEnum];
export const CheckoutExcludeCardNetworksEnum = {
    visa: 'visa',
    mastercard: 'mastercard',
    amex: 'amex',
} as const;

export type CheckoutExcludeCardNetworksEnum = typeof CheckoutExcludeCardNetworksEnum[keyof typeof CheckoutExcludeCardNetworksEnum];


