/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * checkout response
 */
export interface CheckoutResponse {
    /**
     * Are the payment methods available for this link
     */
    'allowed_payment_methods'?: Array<string>;
    /**
     * List of plan IDs that are available for subscription
     */
    'plan_ids'?: Array<string>;
    'can_not_expire'?: boolean;
    'emails_sent'?: number;
    'exclude_card_networks'?: Array<CheckoutResponseExcludeCardNetworksEnum>;
    'expires_at'?: number;
    'failure_url'?: string;
    'force_3ds_flow'?: boolean;
    'id': string;
    'livemode': boolean;
    'metadata'?: { [key: string]: any; };
    'monthly_installments_enabled'?: boolean;
    'monthly_installments_options'?: Array<number>;
    /**
     * Reason for charge
     */
    'name': string;
    'needs_shipping_contact'?: boolean;
    'object': string;
    'paid_payments_count'?: number;
    'payments_limit_count'?: number;
    'recurrent'?: boolean;
    'slug'?: string;
    'sms_sent'?: number;
    'starts_at'?: number;
    'status'?: string;
    /**
     * The URL to redirect to after a successful payment.
     */
    'success_url'?: string;
    'type'?: string;
    'url'?: string;
}

export const CheckoutResponseExcludeCardNetworksEnum = {
    visa: 'visa',
    mastercard: 'mastercard',
    amex: 'amex'
} as const;

export type CheckoutResponseExcludeCardNetworksEnum = typeof CheckoutResponseExcludeCardNetworksEnum[keyof typeof CheckoutResponseExcludeCardNetworksEnum];


