/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Company payout destination model
*/
export class CompanyPayoutDestinationResponse {
    /**
    * The resource\'s type
    */
    'object'?: CompanyPayoutDestinationResponse.ObjectEnum;
    /**
    * currency of the receiving account
    */
    'currency'?: string;
    /**
    * Name of the account holder
    */
    'accountHolderName'?: string;
    /**
    * Name of the bank
    */
    'bank'?: string;
    /**
    * Type of the payout destination
    */
    'type'?: CompanyPayoutDestinationResponse.TypeEnum;
    /**
    * Account number of the receiving account
    */
    'accountNumber'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "CompanyPayoutDestinationResponse.ObjectEnum"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "accountHolderName",
            "baseName": "account_holder_name",
            "type": "string"
        },
        {
            "name": "bank",
            "baseName": "bank",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CompanyPayoutDestinationResponse.TypeEnum"
        },
        {
            "name": "accountNumber",
            "baseName": "account_number",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CompanyPayoutDestinationResponse.attributeTypeMap;
    }
}

export namespace CompanyPayoutDestinationResponse {
    export enum ObjectEnum {
        PayoutDestination = <any> 'payout_destination'
    }
    export enum TypeEnum {
        BankAccount = <any> 'bank_account'
    }
}
