/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaymentMethodCashRequest } from './payment-method-cash-request';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentMethodSpeiRequest } from './payment-method-spei-request';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentMethodTokenRequest } from './payment-method-token-request';

/**
 * @type CustomerPaymentMethodsRequest
 * @export
 */
export type CustomerPaymentMethodsRequest = PaymentMethodCashRequest | PaymentMethodSpeiRequest | PaymentMethodTokenRequest;


