/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerInfo
 */
export interface CustomerInfo {
    /**
     * 
     * @type {string}
     * @memberof CustomerInfo
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfo
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfo
     */
    'phone': string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerInfo
     */
    'corporate'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfo
     */
    'object'?: string;
}

