/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerShippingContactsDataResponseAllOf
 */
export interface CustomerShippingContactsDataResponseAllOf {
    /**
     * 
     * @type {string}
     * @memberof CustomerShippingContactsDataResponseAllOf
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CustomerShippingContactsDataResponseAllOf
     */
    'object': string;
    /**
     * 
     * @type {number}
     * @memberof CustomerShippingContactsDataResponseAllOf
     */
    'created_at': number;
}

