/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CustomerPaymentMethods } from './customer-payment-methods';
// May contain unused imports in some cases
// @ts-ignore
import { CustomerPaymentMethodsData } from './customer-payment-methods-data';
// May contain unused imports in some cases
// @ts-ignore
import { Page } from './page';
// May contain unused imports in some cases
// @ts-ignore
import { Pagination } from './pagination';

/**
 * @type CustomerPaymentMethodsResponse
 * @export
 */
export type CustomerPaymentMethodsResponse = CustomerPaymentMethods & Page & Pagination;


