/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomerResponse } from './customer-response';

/**
 * 
 * @export
 * @interface CustomersResponse
 */
export interface CustomersResponse {
    /**
     * 
     * @type {Array<CustomerResponse>}
     * @memberof CustomersResponse
     */
    'data'?: Array<CustomerResponse>;
    /**
     * Indicates if there are more pages to be requested
     * @type {boolean}
     * @memberof CustomersResponse
     */
    'has_more': boolean;
    /**
     * Object type, in this case is list
     * @type {string}
     * @memberof CustomersResponse
     */
    'object': string;
    /**
     * URL of the next page.
     * @type {string}
     * @memberof CustomersResponse
     */
    'next_page_url'?: string;
    /**
     * Url of the previous page.
     * @type {string}
     * @memberof CustomersResponse
     */
    'previous_page_url'?: string;
}

