/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DiscountLinesResponseAllOf
 */
export interface DiscountLinesResponseAllOf {
    /**
     * The discount line id
     * @type {string}
     * @memberof DiscountLinesResponseAllOf
     */
    'id': string;
    /**
     * The object name
     * @type {string}
     * @memberof DiscountLinesResponseAllOf
     */
    'object': string;
    /**
     * The order id
     * @type {string}
     * @memberof DiscountLinesResponseAllOf
     */
    'parent_id': string;
}

