/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WebhookLog } from './webhookLog';

/**
* event model
*/
export class EventResponse {
    'createdAt'?: number;
    'data'?: { [key: string]: any; };
    'id'?: string;
    'livemode'?: boolean;
    'object'?: string;
    'type'?: string;
    'webhookLogs'?: Array<WebhookLog>;
    'webhookStatus'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "webhookLogs",
            "baseName": "webhook_logs",
            "type": "Array<WebhookLog>"
        },
        {
            "name": "webhookStatus",
            "baseName": "webhook_status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EventResponse.attributeTypeMap;
    }
}

