/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface FiscalEntityRequestAddress {
    'street1': string;
    'street2'?: string;
    'postal_code': string;
    'city': string;
    'state'?: string;
    /**
     * this field follows the [ISO 3166-1 alpha-2 standard](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
     */
    'country'?: string;
    'residential'?: boolean;
    'external_number'?: string;
}

