/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FiscalEntityRequestAddress
 */
export interface FiscalEntityRequestAddress {
    /**
     * 
     * @type {string}
     * @memberof FiscalEntityRequestAddress
     */
    'street1': string;
    /**
     * 
     * @type {string}
     * @memberof FiscalEntityRequestAddress
     */
    'street2'?: string;
    /**
     * 
     * @type {string}
     * @memberof FiscalEntityRequestAddress
     */
    'postal_code': string;
    /**
     * 
     * @type {string}
     * @memberof FiscalEntityRequestAddress
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof FiscalEntityRequestAddress
     */
    'state'?: string;
    /**
     * this field follows the [ISO 3166-1 alpha-2 standard](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
     * @type {string}
     * @memberof FiscalEntityRequestAddress
     */
    'country'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FiscalEntityRequestAddress
     */
    'residential'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FiscalEntityRequestAddress
     */
    'external_number'?: string;
}

