/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WebhookKeyResponse } from './webhook-key-response';

/**
 * 
 * @export
 * @interface GetWebhookKeysResponseAllOf
 */
export interface GetWebhookKeysResponseAllOf {
    /**
     * 
     * @type {Array<WebhookKeyResponse>}
     * @memberof GetWebhookKeysResponseAllOf
     */
    'data'?: Array<WebhookKeyResponse>;
}

