/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApiKeyResponse } from './api-key-response';

/**
 * 
 * @export
 * @interface GetApiKeysResponseAllOf
 */
export interface GetApiKeysResponseAllOf {
    /**
     * 
     * @type {Array<ApiKeyResponse>}
     * @memberof GetApiKeysResponseAllOf
     */
    'data'?: Array<ApiKeyResponse>;
}

