/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ChargesDataResponse } from './chargesDataResponse';

/**
* The charges associated with the order
*/
export class OrderResponseCharges {
    /**
    * Object type, in this case is list
    */
    'object': string;
    /**
    * Indicates if there are more pages to be requested
    */
    'hasMore': boolean;
    'data'?: Array<ChargesDataResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        },
        {
            "name": "hasMore",
            "baseName": "has_more",
            "type": "boolean"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<ChargesDataResponse>"
        }    ];

    static getAttributeTypeMap() {
        return OrderResponseCharges.attributeTypeMap;
    }
}

