/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrderChannelResponse
 */
export interface OrderChannelResponse {
    /**
     * 
     * @type {string}
     * @memberof OrderChannelResponse
     */
    'segment'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderChannelResponse
     */
    'checkout_request_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderChannelResponse
     */
    'checkout_request_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderChannelResponse
     */
    'id'?: string;
}

