/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OrderResponseCheckout {
    'allowedPaymentMethods'?: Array<string>;
    'canNotExpire'?: boolean;
    'emailsSent'?: number;
    'excludeCardNetworks'?: Array<object>;
    'expiresAt'?: number;
    'failureUrl'?: string;
    'force3dsFlow'?: boolean;
    'id'?: string;
    'isRedirectOnFailure'?: boolean;
    'livemode'?: boolean;
    'metadata'?: { [key: string]: any; };
    'monthlyInstallmentsEnabled'?: boolean;
    'monthlyInstallmentsOptions'?: Array<number>;
    'name'?: string;
    'needsShippingContact'?: boolean;
    'object'?: string;
    'onDemandEnabled'?: boolean | null;
    'paidPaymentsCount'?: number;
    'recurrent'?: boolean;
    'slug'?: string;
    'smsSent'?: number;
    'successUrl'?: string;
    'startsAt'?: number;
    'status'?: string;
    'type'?: string;
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allowedPaymentMethods",
            "baseName": "allowed_payment_methods",
            "type": "Array<string>"
        },
        {
            "name": "canNotExpire",
            "baseName": "can_not_expire",
            "type": "boolean"
        },
        {
            "name": "emailsSent",
            "baseName": "emails_sent",
            "type": "number"
        },
        {
            "name": "excludeCardNetworks",
            "baseName": "exclude_card_networks",
            "type": "Array<object>"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "number"
        },
        {
            "name": "failureUrl",
            "baseName": "failure_url",
            "type": "string"
        },
        {
            "name": "force3dsFlow",
            "baseName": "force_3ds_flow",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isRedirectOnFailure",
            "baseName": "is_redirect_on_failure",
            "type": "boolean"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "monthlyInstallmentsEnabled",
            "baseName": "monthly_installments_enabled",
            "type": "boolean"
        },
        {
            "name": "monthlyInstallmentsOptions",
            "baseName": "monthly_installments_options",
            "type": "Array<number>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "needsShippingContact",
            "baseName": "needs_shipping_contact",
            "type": "boolean"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        },
        {
            "name": "onDemandEnabled",
            "baseName": "on_demand_enabled",
            "type": "boolean"
        },
        {
            "name": "paidPaymentsCount",
            "baseName": "paid_payments_count",
            "type": "number"
        },
        {
            "name": "recurrent",
            "baseName": "recurrent",
            "type": "boolean"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "smsSent",
            "baseName": "sms_sent",
            "type": "number"
        },
        {
            "name": "successUrl",
            "baseName": "success_url",
            "type": "string"
        },
        {
            "name": "startsAt",
            "baseName": "starts_at",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OrderResponseCheckout.attributeTypeMap;
    }
}

