/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ChargeOrderResponseChannel } from './chargeOrderResponseChannel';
import { OrderResponseCharges } from './orderResponseCharges';
import { OrderResponseCheckout } from './orderResponseCheckout';
import { OrderResponseCustomerInfo } from './orderResponseCustomerInfo';
import { OrderResponseDiscountLines } from './orderResponseDiscountLines';
import { OrderResponseFiscalEntity } from './orderResponseFiscalEntity';
import { OrderResponseProducts } from './orderResponseProducts';
import { OrderResponseShippingContact } from './orderResponseShippingContact';

/**
* order response
*/
export class OrderResponse {
    /**
    * The total amount to be collected in cents
    */
    'amount'?: number;
    /**
    * The total amount refunded in cents
    */
    'amountRefunded'?: number;
    'channel'?: ChargeOrderResponseChannel;
    'charges'?: OrderResponseCharges;
    'checkout'?: OrderResponseCheckout;
    /**
    * The time at which the object was created in seconds since the Unix epoch
    */
    'createdAt'?: number;
    /**
    * The three-letter ISO 4217 currency code. The currency of the order.
    */
    'currency'?: string;
    'customerInfo'?: OrderResponseCustomerInfo;
    'discountLines'?: OrderResponseDiscountLines;
    'fiscalEntity'?: OrderResponseFiscalEntity;
    'id'?: string;
    'isRefundable'?: boolean;
    'lineItems'?: OrderResponseProducts;
    /**
    * Whether the object exists in live mode or test mode
    */
    'livemode'?: boolean;
    /**
    * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    */
    'metadata'?: { [key: string]: any; };
    /**
    * String representing the object’s type. Objects of the same type share the same value.
    */
    'object'?: string;
    /**
    * The payment status of the order.
    */
    'paymentStatus'?: string;
    'shippingContact'?: OrderResponseShippingContact;
    /**
    * The time at which the object was last updated in seconds since the Unix epoch
    */
    'updatedAt'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "amountRefunded",
            "baseName": "amount_refunded",
            "type": "number"
        },
        {
            "name": "channel",
            "baseName": "channel",
            "type": "ChargeOrderResponseChannel"
        },
        {
            "name": "charges",
            "baseName": "charges",
            "type": "OrderResponseCharges"
        },
        {
            "name": "checkout",
            "baseName": "checkout",
            "type": "OrderResponseCheckout"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "customerInfo",
            "baseName": "customer_info",
            "type": "OrderResponseCustomerInfo"
        },
        {
            "name": "discountLines",
            "baseName": "discount_lines",
            "type": "OrderResponseDiscountLines"
        },
        {
            "name": "fiscalEntity",
            "baseName": "fiscal_entity",
            "type": "OrderResponseFiscalEntity"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isRefundable",
            "baseName": "is_refundable",
            "type": "boolean"
        },
        {
            "name": "lineItems",
            "baseName": "line_items",
            "type": "OrderResponseProducts"
        },
        {
            "name": "livemode",
            "baseName": "livemode",
            "type": "boolean"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        },
        {
            "name": "paymentStatus",
            "baseName": "payment_status",
            "type": "string"
        },
        {
            "name": "shippingContact",
            "baseName": "shipping_contact",
            "type": "OrderResponseShippingContact"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OrderResponse.attributeTypeMap;
    }
}

