/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PaymentMethodBankTransfer {
    'type'?: string;
    'object': string;
    'bank'?: string;
    'clabe'?: string;
    'description'?: string | null;
    'executed_at'?: string | null;
    'expires_at'?: number;
    'issuing_account_bank'?: string | null;
    'issuing_account_number'?: string | null;
    'issuing_account_holder_name'?: string | null;
    'issuing_account_tax_id'?: string | null;
    'payment_attempts'?: Array<any>;
    'receiving_account_holder_name'?: string | null;
    'receiving_account_number'?: string;
    'receiving_account_bank'?: string;
    'receiving_account_tax_id'?: string | null;
    'reference_number'?: string | null;
    'tracking_code'?: string | null;
    'customer_ip_address'?: string;
}

