/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PaymentMethodCard {
    'type'?: string;
    'object': string;
    /**
     * Account type of the card
     */
    'account_type'?: string;
    'auth_code'?: string;
    /**
     * Brand of the card
     */
    'brand'?: string;
    /**
     * Id sent for recurrent charges.
     */
    'contract_id'?: string;
    /**
     * Country of the card
     */
    'country'?: string;
    /**
     * Expiration month of the card
     */
    'exp_month'?: string;
    /**
     * Expiration year of the card
     */
    'exp_year'?: string;
    'fraud_indicators'?: Array<any>;
    /**
     * Issuer of the card
     */
    'issuer'?: string;
    /**
     * Last 4 digits of the card
     */
    'last4'?: string;
    /**
     * Name of the cardholder
     */
    'name'?: string;
    /**
     * Optional field used to capture the customer\'s IP address for fraud prevention and security monitoring purposes
     */
    'customer_ip_address'?: string;
}

