/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentMethodPbbRequest
 */
export interface PaymentMethodPbbRequest {
    /**
     * Type of the payment method
     * @type {string}
     * @memberof PaymentMethodPbbRequest
     */
    'type': string;
    /**
     * Expiration date of the payment method, in Unix timestamp format
     * @type {number}
     * @memberof PaymentMethodPbbRequest
     */
    'expires_at'?: number;
    /**
     * Product type of the payment method, use for the payment method to know the product type
     * @type {string}
     * @memberof PaymentMethodPbbRequest
     */
    'product_type': PaymentMethodPbbRequestProductTypeEnum;
}

export const PaymentMethodPbbRequestProductTypeEnum = {
    bbvaPayByBank: 'bbva_pay_by_bank'
} as const;

export type PaymentMethodPbbRequestProductTypeEnum = typeof PaymentMethodPbbRequestProductTypeEnum[keyof typeof PaymentMethodPbbRequestProductTypeEnum];


