/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomerInfoJustCustomerId } from './customer-info-just-customer-id';
// May contain unused imports in some cases
// @ts-ignore
import type { Payout } from './payout';

/**
 * a payout order
 * @export
 * @interface PayoutOrder
 */
export interface PayoutOrder {
    /**
     * The payout methods that are allowed for the payout order.
     * @type {Array<string>}
     * @memberof PayoutOrder
     */
    'allowed_payout_methods': Array<string>;
    /**
     * The amount of the payout order.
     * @type {number}
     * @memberof PayoutOrder
     */
    'amount': number;
    /**
     * The currency in which the payout order is made.
     * @type {string}
     * @memberof PayoutOrder
     */
    'currency': string;
    /**
     * 
     * @type {CustomerInfoJustCustomerId}
     * @memberof PayoutOrder
     */
    'customer_info': CustomerInfoJustCustomerId;
    /**
     * The metadata of the payout order.
     * @type {{ [key: string]: any; }}
     * @memberof PayoutOrder
     */
    'metadata'?: { [key: string]: any; };
    /**
     * 
     * @type {Payout}
     * @memberof PayoutOrder
     */
    'payout': Payout;
    /**
     * The reason for the payout order.
     * @type {string}
     * @memberof PayoutOrder
     */
    'reason': string;
}

