/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomerInfoCustomerId } from './customer-info-customer-id';
// May contain unused imports in some cases
// @ts-ignore
import type { Payout } from './payout';

/**
 * a payout order
 */
export interface PayoutOrderRequest {
    /**
     * The payout methods that are allowed for the payout order.
     */
    'allowed_payout_methods': Array<string>;
    /**
     * The amount of the payout order.
     */
    'amount': number;
    /**
     * The currency in which the payout order is made.
     */
    'currency': string;
    /**
     * The customer information to whom the payout order is made.
     */
    'customer_info': CustomerInfoCustomerId;
    /**
     * The expiration time of the payout order in Unix timestamp.
     */
    'expires_at': number;
    /**
     * The metadata of the payout order.
     */
    'metadata'?: { [key: string]: any; };
    'payout': Payout;
    /**
     * The reason for the payout order.
     */
    'reason': string;
}

