/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RiskRulesData {
    /**
    * rule id
    */
    'id'?: string;
    /**
    * field to be used for the rule
    */
    'field'?: string;
    /**
    * rule creation date
    */
    'createdAt'?: string;
    /**
    * value to be used for the rule
    */
    'value'?: string;
    /**
    * if the rule is global
    */
    'isGlobal'?: boolean;
    /**
    * if the rule is test
    */
    'isTest'?: boolean;
    /**
    * description of the rule
    */
    'description'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "isGlobal",
            "baseName": "is_global",
            "type": "boolean"
        },
        {
            "name": "isTest",
            "baseName": "is_test",
            "type": "boolean"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RiskRulesData.attributeTypeMap;
    }
}

