/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ShippingOrderResponse
 */
export interface ShippingOrderResponse {
    /**
     * Shipping amount in cents
     * @type {number}
     * @memberof ShippingOrderResponse
     */
    'amount': number;
    /**
     * Carrier name for the shipment
     * @type {string}
     * @memberof ShippingOrderResponse
     */
    'carrier'?: string;
    /**
     * Tracking number can be used to track the shipment
     * @type {string}
     * @memberof ShippingOrderResponse
     */
    'tracking_number'?: string;
    /**
     * Method of shipment
     * @type {string}
     * @memberof ShippingOrderResponse
     */
    'method'?: string;
    /**
     * Hash where the user can send additional information for each \'shipping\'.
     * @type {{ [key: string]: any; }}
     * @memberof ShippingOrderResponse
     */
    'metadata'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof ShippingOrderResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingOrderResponse
     */
    'object'?: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingOrderResponse
     */
    'parent_id'?: string;
}

