/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TokenResponseCheckout } from './token-response-checkout';

/**
 * token response
 */
export interface TokenResponse {
    /**
     * @deprecated
     */
    'checkout'?: TokenResponseCheckout;
    /**
     * Unique identifier for the token generated by Conekta.
     */
    'id': string;
    /**
     * Indicates whether the token is in live mode or test mode.
     */
    'livemode': boolean;
    /**
     * Indicates the type of object, in this case token
     */
    'object': string;
    /**
     * Indicates if the token has been used
     */
    'used': boolean;
}

