/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateProduct {
    'antifraud_info'?: { [key: string]: object; };
    'description'?: string;
    'sku'?: string;
    'name'?: string;
    'unit_price'?: number;
    'quantity'?: number;
    'tags'?: Array<string>;
    'brand'?: string;
    'metadata'?: { [key: string]: string; };
}

