/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * webhooks model
 */
export interface WebhookResponse {
    /**
     * id of the webhook
     */
    'id'?: string;
    /**
     * A name or brief explanation of what this webhook is used for
     */
    'description'?: string;
    /**
     * Indicates if the webhook is in production
     */
    'livemode'?: boolean;
    /**
     * Indicates if the webhook is actived or not
     */
    'active'?: boolean;
    /**
     * Object name, value is \'webhook\'
     */
    'object'?: string;
    /**
     * Indicates if the webhook is ready to receive events or failing
     */
    'status'?: string;
    /**
     * lists the events that will be sent to the webhook
     */
    'subscribed_events'?: Array<string>;
    /**
     * url or endpoint of the webhook
     */
    'url'?: string;
}

