kind: pipeline
type: docker
name: Node.js CI

trigger:
  event:
    - push

platform:
  os: linux
  arch: amd64

steps:
  - name: execute Test
    image: node:14
    commands:
      - npm install
      - make test
    environment:
      BASE_PATH: http://mockoon:3000
  - name: report coverage
    image: node:20
    commands:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - ./cc-test-reporter after-build --exit-code $?
    environment:
      CC_TEST_REPORTER_ID: 
        from_secret: CC_TEST_REPORTER_ID
    depends_on:
      - execute Test

services:
- name: mockoon
  image: mockoon/cli
  commands: 
    - mockoon-cli start --data https://raw.githubusercontent.com/conekta/openapi/testing-drone-node/mocks/conekta_api.json --port 3000
