/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChargeResponseRefundsData
 */
export interface ChargeResponseRefundsData {
    /**
     * 
     * @type {number}
     * @memberof ChargeResponseRefundsData
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof ChargeResponseRefundsData
     */
    authCode?: string;
    /**
     * 
     * @type {number}
     * @memberof ChargeResponseRefundsData
     */
    createdAt: number;
    /**
     * refund expiration date
     * @type {number}
     * @memberof ChargeResponseRefundsData
     */
    expiresAt?: number;
    /**
     * 
     * @type {string}
     * @memberof ChargeResponseRefundsData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ChargeResponseRefundsData
     */
    object: string;
    /**
     * refund status
     * @type {string}
     * @memberof ChargeResponseRefundsData
     */
    status?: string;
}

/**
 * Check if a given object implements the ChargeResponseRefundsData interface.
 */
export function instanceOfChargeResponseRefundsData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "object" in value;

    return isInstance;
}

export function ChargeResponseRefundsDataFromJSON(json: any): ChargeResponseRefundsData {
    return ChargeResponseRefundsDataFromJSONTyped(json, false);
}

export function ChargeResponseRefundsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChargeResponseRefundsData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'authCode': !exists(json, 'auth_code') ? undefined : json['auth_code'],
        'createdAt': json['created_at'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : json['expires_at'],
        'id': json['id'],
        'object': json['object'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ChargeResponseRefundsDataToJSON(value?: ChargeResponseRefundsData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'auth_code': value.authCode,
        'created_at': value.createdAt,
        'expires_at': value.expiresAt,
        'id': value.id,
        'object': value.object,
        'status': value.status,
    };
}

