/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CustomerShippingContactsAddress } from './CustomerShippingContactsAddress';
import {
    CustomerShippingContactsAddressFromJSON,
    CustomerShippingContactsAddressFromJSONTyped,
    CustomerShippingContactsAddressToJSON,
} from './CustomerShippingContactsAddress';

/**
 * 
 * @export
 * @interface CustomerShippingContactsDataResponse
 */
export interface CustomerShippingContactsDataResponse {
    /**
     * Phone contact
     * @type {string}
     * @memberof CustomerShippingContactsDataResponse
     */
    phone?: string;
    /**
     * Name of the person who will receive the order
     * @type {string}
     * @memberof CustomerShippingContactsDataResponse
     */
    receiver?: string;
    /**
     * The street names between which the order will be delivered.
     * @type {string}
     * @memberof CustomerShippingContactsDataResponse
     */
    betweenStreets?: string;
    /**
     * 
     * @type {CustomerShippingContactsAddress}
     * @memberof CustomerShippingContactsDataResponse
     */
    address: CustomerShippingContactsAddress;
    /**
     * 
     * @type {string}
     * @memberof CustomerShippingContactsDataResponse
     */
    parentId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerShippingContactsDataResponse
     */
    _default?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerShippingContactsDataResponse
     */
    deleted?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerShippingContactsDataResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerShippingContactsDataResponse
     */
    object: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerShippingContactsDataResponse
     */
    createdAt: number;
}

/**
 * Check if a given object implements the CustomerShippingContactsDataResponse interface.
 */
export function instanceOfCustomerShippingContactsDataResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "object" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function CustomerShippingContactsDataResponseFromJSON(json: any): CustomerShippingContactsDataResponse {
    return CustomerShippingContactsDataResponseFromJSONTyped(json, false);
}

export function CustomerShippingContactsDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerShippingContactsDataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'receiver': !exists(json, 'receiver') ? undefined : json['receiver'],
        'betweenStreets': !exists(json, 'between_streets') ? undefined : json['between_streets'],
        'address': CustomerShippingContactsAddressFromJSON(json['address']),
        'parentId': !exists(json, 'parent_id') ? undefined : json['parent_id'],
        '_default': !exists(json, 'default') ? undefined : json['default'],
        'deleted': !exists(json, 'deleted') ? undefined : json['deleted'],
        'id': json['id'],
        'object': json['object'],
        'createdAt': json['created_at'],
    };
}

export function CustomerShippingContactsDataResponseToJSON(value?: CustomerShippingContactsDataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'phone': value.phone,
        'receiver': value.receiver,
        'between_streets': value.betweenStreets,
        'address': CustomerShippingContactsAddressToJSON(value.address),
        'parent_id': value.parentId,
        'default': value._default,
        'deleted': value.deleted,
        'id': value.id,
        'object': value.object,
        'created_at': value.createdAt,
    };
}

