/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerAddress
 */
export interface CustomerAddress {
    /**
     * 
     * @type {string}
     * @memberof CustomerAddress
     */
    street1: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddress
     */
    street2?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddress
     */
    postalCode: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddress
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddress
     */
    state?: string;
    /**
     * this field follows the [ISO 3166-1 alpha-2 standard](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
     * @type {string}
     * @memberof CustomerAddress
     */
    country?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerAddress
     */
    residential?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddress
     */
    externalNumber?: string;
}

/**
 * Check if a given object implements the CustomerAddress interface.
 */
export function instanceOfCustomerAddress(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "street1" in value;
    isInstance = isInstance && "postalCode" in value;
    isInstance = isInstance && "city" in value;

    return isInstance;
}

export function CustomerAddressFromJSON(json: any): CustomerAddress {
    return CustomerAddressFromJSONTyped(json, false);
}

export function CustomerAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'street1': json['street1'],
        'street2': !exists(json, 'street2') ? undefined : json['street2'],
        'postalCode': json['postal_code'],
        'city': json['city'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'residential': !exists(json, 'residential') ? undefined : json['residential'],
        'externalNumber': !exists(json, 'external_number') ? undefined : json['external_number'],
    };
}

export function CustomerAddressToJSON(value?: CustomerAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'street1': value.street1,
        'street2': value.street2,
        'postal_code': value.postalCode,
        'city': value.city,
        'state': value.state,
        'country': value.country,
        'residential': value.residential,
        'external_number': value.externalNumber,
    };
}

