/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CompanyResponse } from './CompanyResponse';
import {
    CompanyResponseFromJSON,
    CompanyResponseFromJSONTyped,
    CompanyResponseToJSON,
} from './CompanyResponse';

/**
 * 
 * @export
 * @interface GetCompaniesResponse
 */
export interface GetCompaniesResponse {
    /**
     * Object type, in this case is list
     * @type {string}
     * @memberof GetCompaniesResponse
     */
    object: string;
    /**
     * Indicates if there are more pages to be requested
     * @type {boolean}
     * @memberof GetCompaniesResponse
     */
    hasMore: boolean;
    /**
     * URL of the next page.
     * @type {string}
     * @memberof GetCompaniesResponse
     */
    nextPageUrl?: string | null;
    /**
     * Url of the previous page.
     * @type {string}
     * @memberof GetCompaniesResponse
     */
    previousPageUrl?: string | null;
    /**
     * 
     * @type {Array<CompanyResponse>}
     * @memberof GetCompaniesResponse
     */
    data?: Array<CompanyResponse>;
}

/**
 * Check if a given object implements the GetCompaniesResponse interface.
 */
export function instanceOfGetCompaniesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "object" in value;
    isInstance = isInstance && "hasMore" in value;

    return isInstance;
}

export function GetCompaniesResponseFromJSON(json: any): GetCompaniesResponse {
    return GetCompaniesResponseFromJSONTyped(json, false);
}

export function GetCompaniesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCompaniesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'object': json['object'],
        'hasMore': json['has_more'],
        'nextPageUrl': !exists(json, 'next_page_url') ? undefined : json['next_page_url'],
        'previousPageUrl': !exists(json, 'previous_page_url') ? undefined : json['previous_page_url'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(CompanyResponseFromJSON)),
    };
}

export function GetCompaniesResponseToJSON(value?: GetCompaniesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'object': value.object,
        'has_more': value.hasMore,
        'next_page_url': value.nextPageUrl,
        'previous_page_url': value.previousPageUrl,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(CompanyResponseToJSON)),
    };
}

