/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderResponse } from './OrderResponse';
import {
    OrderResponseFromJSON,
    OrderResponseFromJSONTyped,
    OrderResponseToJSON,
} from './OrderResponse';

/**
 * 
 * @export
 * @interface GetOrdersResponse
 */
export interface GetOrdersResponse {
    /**
     * 
     * @type {Array<OrderResponse>}
     * @memberof GetOrdersResponse
     */
    data: Array<OrderResponse>;
    /**
     * Object type, in this case is list
     * @type {string}
     * @memberof GetOrdersResponse
     */
    object: string;
    /**
     * Indicates if there are more pages to be requested
     * @type {boolean}
     * @memberof GetOrdersResponse
     */
    hasMore: boolean;
    /**
     * URL of the next page.
     * @type {string}
     * @memberof GetOrdersResponse
     */
    nextPageUrl?: string | null;
    /**
     * Url of the previous page.
     * @type {string}
     * @memberof GetOrdersResponse
     */
    previousPageUrl?: string | null;
}

/**
 * Check if a given object implements the GetOrdersResponse interface.
 */
export function instanceOfGetOrdersResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "object" in value;
    isInstance = isInstance && "hasMore" in value;

    return isInstance;
}

export function GetOrdersResponseFromJSON(json: any): GetOrdersResponse {
    return GetOrdersResponseFromJSONTyped(json, false);
}

export function GetOrdersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrdersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(OrderResponseFromJSON)),
        'object': json['object'],
        'hasMore': json['has_more'],
        'nextPageUrl': !exists(json, 'next_page_url') ? undefined : json['next_page_url'],
        'previousPageUrl': !exists(json, 'previous_page_url') ? undefined : json['previous_page_url'],
    };
}

export function GetOrdersResponseToJSON(value?: GetOrdersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(OrderResponseToJSON)),
        'object': value.object,
        'has_more': value.hasMore,
        'next_page_url': value.nextPageUrl,
        'previous_page_url': value.previousPageUrl,
    };
}

