/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCustomerPaymentMethodDataResponse } from './GetCustomerPaymentMethodDataResponse';
import {
    GetCustomerPaymentMethodDataResponseFromJSON,
    GetCustomerPaymentMethodDataResponseFromJSONTyped,
    GetCustomerPaymentMethodDataResponseToJSON,
} from './GetCustomerPaymentMethodDataResponse';

/**
 * 
 * @export
 * @interface GetPaymentMethodResponseAllOf
 */
export interface GetPaymentMethodResponseAllOf {
    /**
     * 
     * @type {Array<GetCustomerPaymentMethodDataResponse>}
     * @memberof GetPaymentMethodResponseAllOf
     */
    data?: Array<GetCustomerPaymentMethodDataResponse>;
}

/**
 * Check if a given object implements the GetPaymentMethodResponseAllOf interface.
 */
export function instanceOfGetPaymentMethodResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPaymentMethodResponseAllOfFromJSON(json: any): GetPaymentMethodResponseAllOf {
    return GetPaymentMethodResponseAllOfFromJSONTyped(json, false);
}

export function GetPaymentMethodResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPaymentMethodResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(GetCustomerPaymentMethodDataResponseFromJSON)),
    };
}

export function GetPaymentMethodResponseAllOfToJSON(value?: GetPaymentMethodResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(GetCustomerPaymentMethodDataResponseToJSON)),
    };
}

