/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogsResponseData
 */
export interface LogsResponseData {
    /**
     * 
     * @type {number}
     * @memberof LogsResponseData
     */
    createdAt?: number;
    /**
     * 
     * @type {string}
     * @memberof LogsResponseData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LogsResponseData
     */
    ipAddress?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LogsResponseData
     */
    livemode?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LogsResponseData
     */
    loggableId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LogsResponseData
     */
    loggableType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LogsResponseData
     */
    method?: string;
    /**
     * 
     * @type {string}
     * @memberof LogsResponseData
     */
    oauthTokenId?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LogsResponseData
     */
    queryString?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof LogsResponseData
     */
    related?: string;
    /**
     * 
     * @type {object}
     * @memberof LogsResponseData
     */
    requestBody?: object;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LogsResponseData
     */
    requestHeaders?: { [key: string]: string; };
    /**
     * 
     * @type {object}
     * @memberof LogsResponseData
     */
    responseBody?: object;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LogsResponseData
     */
    responseHeaders?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof LogsResponseData
     */
    searchableTags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof LogsResponseData
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof LogsResponseData
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof LogsResponseData
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof LogsResponseData
     */
    userAccountId?: string;
    /**
     * 
     * @type {string}
     * @memberof LogsResponseData
     */
    version?: string;
}

/**
 * Check if a given object implements the LogsResponseData interface.
 */
export function instanceOfLogsResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LogsResponseDataFromJSON(json: any): LogsResponseData {
    return LogsResponseDataFromJSONTyped(json, false);
}

export function LogsResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogsResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ipAddress': !exists(json, 'ip_address') ? undefined : json['ip_address'],
        'livemode': !exists(json, 'livemode') ? undefined : json['livemode'],
        'loggableId': !exists(json, 'loggable_id') ? undefined : json['loggable_id'],
        'loggableType': !exists(json, 'loggable_type') ? undefined : json['loggable_type'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'oauthTokenId': !exists(json, 'oauth_token_id') ? undefined : json['oauth_token_id'],
        'queryString': !exists(json, 'query_string') ? undefined : json['query_string'],
        'related': !exists(json, 'related') ? undefined : json['related'],
        'requestBody': !exists(json, 'request_body') ? undefined : json['request_body'],
        'requestHeaders': !exists(json, 'request_headers') ? undefined : json['request_headers'],
        'responseBody': !exists(json, 'response_body') ? undefined : json['response_body'],
        'responseHeaders': !exists(json, 'response_headers') ? undefined : json['response_headers'],
        'searchableTags': !exists(json, 'searchable_tags') ? undefined : json['searchable_tags'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'updatedAt': !exists(json, 'updated_at') ? undefined : json['updated_at'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'userAccountId': !exists(json, 'user_account_id') ? undefined : json['user_account_id'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function LogsResponseDataToJSON(value?: LogsResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt,
        'id': value.id,
        'ip_address': value.ipAddress,
        'livemode': value.livemode,
        'loggable_id': value.loggableId,
        'loggable_type': value.loggableType,
        'method': value.method,
        'oauth_token_id': value.oauthTokenId,
        'query_string': value.queryString,
        'related': value.related,
        'request_body': value.requestBody,
        'request_headers': value.requestHeaders,
        'response_body': value.responseBody,
        'response_headers': value.responseHeaders,
        'searchable_tags': value.searchableTags,
        'status': value.status,
        'updated_at': value.updatedAt,
        'url': value.url,
        'user_account_id': value.userAccountId,
        'version': value.version,
    };
}

