/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiscountLinesDataResponse } from './DiscountLinesDataResponse';
import {
    DiscountLinesDataResponseFromJSON,
    DiscountLinesDataResponseFromJSONTyped,
    DiscountLinesDataResponseToJSON,
} from './DiscountLinesDataResponse';

/**
 * 
 * @export
 * @interface OrderResponseDiscountLines
 */
export interface OrderResponseDiscountLines {
    /**
     * Object type, in this case is list
     * @type {string}
     * @memberof OrderResponseDiscountLines
     */
    object: string;
    /**
     * Indicates if there are more pages to be requested
     * @type {boolean}
     * @memberof OrderResponseDiscountLines
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<DiscountLinesDataResponse>}
     * @memberof OrderResponseDiscountLines
     */
    data?: Array<DiscountLinesDataResponse>;
}

/**
 * Check if a given object implements the OrderResponseDiscountLines interface.
 */
export function instanceOfOrderResponseDiscountLines(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "object" in value;
    isInstance = isInstance && "hasMore" in value;

    return isInstance;
}

export function OrderResponseDiscountLinesFromJSON(json: any): OrderResponseDiscountLines {
    return OrderResponseDiscountLinesFromJSONTyped(json, false);
}

export function OrderResponseDiscountLinesFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderResponseDiscountLines {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'object': json['object'],
        'hasMore': json['has_more'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(DiscountLinesDataResponseFromJSON)),
    };
}

export function OrderResponseDiscountLinesToJSON(value?: OrderResponseDiscountLines | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'object': value.object,
        'has_more': value.hasMore,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(DiscountLinesDataResponseToJSON)),
    };
}

