/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderCaptureRequest
 */
export interface OrderCaptureRequest {
    /**
     * Amount to capture
     * @type {number}
     * @memberof OrderCaptureRequest
     */
    amount: number;
}

/**
 * Check if a given object implements the OrderCaptureRequest interface.
 */
export function instanceOfOrderCaptureRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;

    return isInstance;
}

export function OrderCaptureRequestFromJSON(json: any): OrderCaptureRequest {
    return OrderCaptureRequestFromJSONTyped(json, false);
}

export function OrderCaptureRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderCaptureRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
    };
}

export function OrderCaptureRequestToJSON(value?: OrderCaptureRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
    };
}

