/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderResponse } from './OrderResponse';
import {
    OrderResponseFromJSON,
    OrderResponseFromJSONTyped,
    OrderResponseToJSON,
} from './OrderResponse';

/**
 * 
 * @export
 * @interface OrdersResponse
 */
export interface OrdersResponse {
    /**
     * 
     * @type {Array<OrderResponse>}
     * @memberof OrdersResponse
     */
    data: Array<OrderResponse>;
}

/**
 * Check if a given object implements the OrdersResponse interface.
 */
export function instanceOfOrdersResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function OrdersResponseFromJSON(json: any): OrdersResponse {
    return OrdersResponseFromJSONTyped(json, false);
}

export function OrdersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrdersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(OrderResponseFromJSON)),
    };
}

export function OrdersResponseToJSON(value?: OrdersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(OrderResponseToJSON)),
    };
}

