/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentMethodCashRequest
 */
export interface PaymentMethodCashRequest {
    /**
     * Type of payment method
     * @type {string}
     * @memberof PaymentMethodCashRequest
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentMethodCashRequest
     */
    expiresAt?: number;
}

/**
 * Check if a given object implements the PaymentMethodCashRequest interface.
 */
export function instanceOfPaymentMethodCashRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function PaymentMethodCashRequestFromJSON(json: any): PaymentMethodCashRequest {
    return PaymentMethodCashRequestFromJSONTyped(json, false);
}

export function PaymentMethodCashRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodCashRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : json['expires_at'],
    };
}

export function PaymentMethodCashRequestToJSON(value?: PaymentMethodCashRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'expires_at': value.expiresAt,
    };
}

