/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RiskRulesData } from './RiskRulesData';
import {
    RiskRulesDataFromJSON,
    RiskRulesDataFromJSONTyped,
    RiskRulesDataToJSON,
} from './RiskRulesData';

/**
 * 
 * @export
 * @interface RiskRules
 */
export interface RiskRules {
    /**
     * 
     * @type {Array<RiskRulesData>}
     * @memberof RiskRules
     */
    data?: Array<RiskRulesData>;
}

/**
 * Check if a given object implements the RiskRules interface.
 */
export function instanceOfRiskRules(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RiskRulesFromJSON(json: any): RiskRules {
    return RiskRulesFromJSONTyped(json, false);
}

export function RiskRulesFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskRules {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(RiskRulesDataFromJSON)),
    };
}

export function RiskRulesToJSON(value?: RiskRules | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(RiskRulesDataToJSON)),
    };
}

