/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SmsCheckoutRequest
 */
export interface SmsCheckoutRequest {
    /**
     * 
     * @type {string}
     * @memberof SmsCheckoutRequest
     */
    phonenumber: string;
}

/**
 * Check if a given object implements the SmsCheckoutRequest interface.
 */
export function instanceOfSmsCheckoutRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "phonenumber" in value;

    return isInstance;
}

export function SmsCheckoutRequestFromJSON(json: any): SmsCheckoutRequest {
    return SmsCheckoutRequestFromJSONTyped(json, false);
}

export function SmsCheckoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmsCheckoutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'phonenumber': json['phonenumber'],
    };
}

export function SmsCheckoutRequestToJSON(value?: SmsCheckoutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'phonenumber': value.phonenumber,
    };
}

