/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenCard
 */
export interface TokenCard {
    /**
     * It is a value that allows identifying the security code of the card.
     * @type {string}
     * @memberof TokenCard
     */
    cvc: string;
    /**
     * It is a value that allows identifying the device fingerprint.
     * @type {string}
     * @memberof TokenCard
     */
    deviceFingerprint?: string;
    /**
     * It is a value that allows identifying the expiration month of the card.
     * @type {string}
     * @memberof TokenCard
     */
    expMonth: string;
    /**
     * It is a value that allows identifying the expiration year of the card.
     * @type {string}
     * @memberof TokenCard
     */
    expYear: string;
    /**
     * It is a value that allows identifying the name of the cardholder.
     * @type {string}
     * @memberof TokenCard
     */
    name: string;
    /**
     * It is a value that allows identifying the number of the card.
     * @type {string}
     * @memberof TokenCard
     */
    number: string;
}

/**
 * Check if a given object implements the TokenCard interface.
 */
export function instanceOfTokenCard(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cvc" in value;
    isInstance = isInstance && "expMonth" in value;
    isInstance = isInstance && "expYear" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "number" in value;

    return isInstance;
}

export function TokenCardFromJSON(json: any): TokenCard {
    return TokenCardFromJSONTyped(json, false);
}

export function TokenCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cvc': json['cvc'],
        'deviceFingerprint': !exists(json, 'device_fingerprint') ? undefined : json['device_fingerprint'],
        'expMonth': json['exp_month'],
        'expYear': json['exp_year'],
        'name': json['name'],
        'number': json['number'],
    };
}

export function TokenCardToJSON(value?: TokenCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cvc': value.cvc,
        'device_fingerprint': value.deviceFingerprint,
        'exp_month': value.expMonth,
        'exp_year': value.expYear,
        'name': value.name,
        'number': value.number,
    };
}

