/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * webhook keys model
 * @export
 * @interface WebhookKeyCreateResponse
 */
export interface WebhookKeyCreateResponse {
    /**
     * Indicates if the webhook key is active
     * @type {boolean}
     * @memberof WebhookKeyCreateResponse
     */
    active?: boolean;
    /**
     * Unix timestamp in seconds with the creation date of the webhook key
     * @type {number}
     * @memberof WebhookKeyCreateResponse
     */
    createdAt?: number;
    /**
     * Unique identifier of the webhook key
     * @type {string}
     * @memberof WebhookKeyCreateResponse
     */
    id?: string;
    /**
     * Indicates if the webhook key is in live mode
     * @type {boolean}
     * @memberof WebhookKeyCreateResponse
     */
    livemode?: boolean;
    /**
     * Object name, value is webhook_key
     * @type {string}
     * @memberof WebhookKeyCreateResponse
     */
    object?: string;
    /**
     * Public key to be used in the webhook
     * @type {string}
     * @memberof WebhookKeyCreateResponse
     */
    publicKey?: string;
}

/**
 * Check if a given object implements the WebhookKeyCreateResponse interface.
 */
export function instanceOfWebhookKeyCreateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebhookKeyCreateResponseFromJSON(json: any): WebhookKeyCreateResponse {
    return WebhookKeyCreateResponseFromJSONTyped(json, false);
}

export function WebhookKeyCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookKeyCreateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'active': !exists(json, 'active') ? undefined : json['active'],
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'livemode': !exists(json, 'livemode') ? undefined : json['livemode'],
        'object': !exists(json, 'object') ? undefined : json['object'],
        'publicKey': !exists(json, 'public_key') ? undefined : json['public_key'],
    };
}

export function WebhookKeyCreateResponseToJSON(value?: WebhookKeyCreateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active': value.active,
        'created_at': value.createdAt,
        'id': value.id,
        'livemode': value.livemode,
        'object': value.object,
        'public_key': value.publicKey,
    };
}

