/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ModelError } from '../model';
// @ts-ignore
import type { MonthlyInstallmentsValidateRequest } from '../model';
// @ts-ignore
import type { MonthlyInstallmentsValidateResponse } from '../model';
/**
 * MonthlyInstallmentsApi - axios parameter creator
 */
export const MonthlyInstallmentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns the interest-free monthly installment plans available for a card BIN and an amount, so a checkout can offer only the plans a later charge will accept. Requires monthly installments to be enabled on the company. 
         * @summary Validate Monthly Installments
         * @param {MonthlyInstallmentsValidateRequest} monthlyInstallmentsValidateRequest requested field for monthly installments validate
         * @param {ValidateMonthlyInstallmentsAcceptLanguageEnum} [acceptLanguage] Use for knowing which language to use
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateMonthlyInstallments: async (monthlyInstallmentsValidateRequest: MonthlyInstallmentsValidateRequest, acceptLanguage?: ValidateMonthlyInstallmentsAcceptLanguageEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'monthlyInstallmentsValidateRequest' is not null or undefined
            assertParamExists('validateMonthlyInstallments', 'monthlyInstallmentsValidateRequest', monthlyInstallmentsValidateRequest)
            const localVarPath = `/monthly_installments/validate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/vnd.conekta-v2.3.0+json';

            if (acceptLanguage != null) {
                localVarHeaderParameter['Accept-Language'] = String(acceptLanguage);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(monthlyInstallmentsValidateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MonthlyInstallmentsApi - functional programming interface
 */
export const MonthlyInstallmentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MonthlyInstallmentsApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns the interest-free monthly installment plans available for a card BIN and an amount, so a checkout can offer only the plans a later charge will accept. Requires monthly installments to be enabled on the company. 
         * @summary Validate Monthly Installments
         * @param {MonthlyInstallmentsValidateRequest} monthlyInstallmentsValidateRequest requested field for monthly installments validate
         * @param {ValidateMonthlyInstallmentsAcceptLanguageEnum} [acceptLanguage] Use for knowing which language to use
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateMonthlyInstallments(monthlyInstallmentsValidateRequest: MonthlyInstallmentsValidateRequest, acceptLanguage?: ValidateMonthlyInstallmentsAcceptLanguageEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MonthlyInstallmentsValidateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.validateMonthlyInstallments(monthlyInstallmentsValidateRequest, acceptLanguage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MonthlyInstallmentsApi.validateMonthlyInstallments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MonthlyInstallmentsApi - factory interface
 */
export const MonthlyInstallmentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MonthlyInstallmentsApiFp(configuration)
    return {
        /**
         * Returns the interest-free monthly installment plans available for a card BIN and an amount, so a checkout can offer only the plans a later charge will accept. Requires monthly installments to be enabled on the company. 
         * @summary Validate Monthly Installments
         * @param {MonthlyInstallmentsValidateRequest} monthlyInstallmentsValidateRequest requested field for monthly installments validate
         * @param {ValidateMonthlyInstallmentsAcceptLanguageEnum} [acceptLanguage] Use for knowing which language to use
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateMonthlyInstallments(monthlyInstallmentsValidateRequest: MonthlyInstallmentsValidateRequest, acceptLanguage?: ValidateMonthlyInstallmentsAcceptLanguageEnum, options?: RawAxiosRequestConfig): AxiosPromise<MonthlyInstallmentsValidateResponse> {
            return localVarFp.validateMonthlyInstallments(monthlyInstallmentsValidateRequest, acceptLanguage, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MonthlyInstallmentsApi - interface
 */
export interface MonthlyInstallmentsApiInterface {
    /**
     * Returns the interest-free monthly installment plans available for a card BIN and an amount, so a checkout can offer only the plans a later charge will accept. Requires monthly installments to be enabled on the company. 
     * @summary Validate Monthly Installments
     * @param {MonthlyInstallmentsValidateRequest} monthlyInstallmentsValidateRequest requested field for monthly installments validate
     * @param {ValidateMonthlyInstallmentsAcceptLanguageEnum} [acceptLanguage] Use for knowing which language to use
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    validateMonthlyInstallments(monthlyInstallmentsValidateRequest: MonthlyInstallmentsValidateRequest, acceptLanguage?: ValidateMonthlyInstallmentsAcceptLanguageEnum, options?: RawAxiosRequestConfig): AxiosPromise<MonthlyInstallmentsValidateResponse>;

}

/**
 * MonthlyInstallmentsApi - object-oriented interface
 */
export class MonthlyInstallmentsApi extends BaseAPI implements MonthlyInstallmentsApiInterface {
    /**
     * Returns the interest-free monthly installment plans available for a card BIN and an amount, so a checkout can offer only the plans a later charge will accept. Requires monthly installments to be enabled on the company. 
     * @summary Validate Monthly Installments
     * @param {MonthlyInstallmentsValidateRequest} monthlyInstallmentsValidateRequest requested field for monthly installments validate
     * @param {ValidateMonthlyInstallmentsAcceptLanguageEnum} [acceptLanguage] Use for knowing which language to use
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public validateMonthlyInstallments(monthlyInstallmentsValidateRequest: MonthlyInstallmentsValidateRequest, acceptLanguage?: ValidateMonthlyInstallmentsAcceptLanguageEnum, options?: RawAxiosRequestConfig) {
        return MonthlyInstallmentsApiFp(this.configuration).validateMonthlyInstallments(monthlyInstallmentsValidateRequest, acceptLanguage, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ValidateMonthlyInstallmentsAcceptLanguageEnum = {
    es: 'es',
    en: 'en',
} as const;
export type ValidateMonthlyInstallmentsAcceptLanguageEnum = typeof ValidateMonthlyInstallmentsAcceptLanguageEnum[keyof typeof ValidateMonthlyInstallmentsAcceptLanguageEnum];
