/* tslint:disable */
/* eslint-disable */
/**
 * Conekta API
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ModelError } from '../model';
// @ts-ignore
import type { TokenRequest } from '../model';
// @ts-ignore
import type { TokenResponse } from '../model';
/**
 * TokensApi - axios parameter creator
 */
export const TokensApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Generate a payment token, to associate it with a card, Endpoint could be use directly only for PCI compliance account 
         * @summary Create Token
         * @param {TokenRequest} tokenRequest requested field for token
         * @param {CreateTokenAcceptLanguageEnum} [acceptLanguage] Use for knowing which language to use
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createToken: async (tokenRequest: TokenRequest, acceptLanguage?: CreateTokenAcceptLanguageEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tokenRequest' is not null or undefined
            assertParamExists('createToken', 'tokenRequest', tokenRequest)
            const localVarPath = `/tokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/vnd.conekta-v2.2.0+json';

            if (acceptLanguage != null) {
                localVarHeaderParameter['Accept-Language'] = String(acceptLanguage);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(tokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TokensApi - functional programming interface
 */
export const TokensApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TokensApiAxiosParamCreator(configuration)
    return {
        /**
         * Generate a payment token, to associate it with a card, Endpoint could be use directly only for PCI compliance account 
         * @summary Create Token
         * @param {TokenRequest} tokenRequest requested field for token
         * @param {CreateTokenAcceptLanguageEnum} [acceptLanguage] Use for knowing which language to use
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createToken(tokenRequest: TokenRequest, acceptLanguage?: CreateTokenAcceptLanguageEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createToken(tokenRequest, acceptLanguage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TokensApi.createToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TokensApi - factory interface
 */
export const TokensApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TokensApiFp(configuration)
    return {
        /**
         * Generate a payment token, to associate it with a card, Endpoint could be use directly only for PCI compliance account 
         * @summary Create Token
         * @param {TokenRequest} tokenRequest requested field for token
         * @param {CreateTokenAcceptLanguageEnum} [acceptLanguage] Use for knowing which language to use
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createToken(tokenRequest: TokenRequest, acceptLanguage?: CreateTokenAcceptLanguageEnum, options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse> {
            return localVarFp.createToken(tokenRequest, acceptLanguage, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TokensApi - interface
 */
export interface TokensApiInterface {
    /**
     * Generate a payment token, to associate it with a card, Endpoint could be use directly only for PCI compliance account 
     * @summary Create Token
     * @param {TokenRequest} tokenRequest requested field for token
     * @param {CreateTokenAcceptLanguageEnum} [acceptLanguage] Use for knowing which language to use
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createToken(tokenRequest: TokenRequest, acceptLanguage?: CreateTokenAcceptLanguageEnum, options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse>;

}

/**
 * TokensApi - object-oriented interface
 */
export class TokensApi extends BaseAPI implements TokensApiInterface {
    /**
     * Generate a payment token, to associate it with a card, Endpoint could be use directly only for PCI compliance account 
     * @summary Create Token
     * @param {TokenRequest} tokenRequest requested field for token
     * @param {CreateTokenAcceptLanguageEnum} [acceptLanguage] Use for knowing which language to use
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createToken(tokenRequest: TokenRequest, acceptLanguage?: CreateTokenAcceptLanguageEnum, options?: RawAxiosRequestConfig) {
        return TokensApiFp(this.configuration).createToken(tokenRequest, acceptLanguage, options).then((request) => request(this.axios, this.basePath));
    }
}

export const CreateTokenAcceptLanguageEnum = {
    es: 'es',
    en: 'en'
} as const;
export type CreateTokenAcceptLanguageEnum = typeof CreateTokenAcceptLanguageEnum[keyof typeof CreateTokenAcceptLanguageEnum];
